import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar for the Etch Studio documentation instance.
 *
 * Etch Studio and Etch WP are separate products, not versions of one another.
 * This sidebar is autogenerated from `studio-docs/`, mirroring how the Etch WP
 * sidebar is built from `docs/`.
 */
const sidebars: SidebarsConfig = {
	studioSidebar: [{ type: 'autogenerated', dirName: '.' }]
};

export default sidebars;
